config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :pages
  resources :links
  root :to => "pages#index"  

end

app/models/link.rb
class Link < ActiveRecord::Base


	belongs_to :user


	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   has_many :links

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def show

  end

  def new

  	@link = Link.new

  end

  def create
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	 def index
  		
  		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%# user is logged in, show log out link %>
  <% if current_user.present? %>
    <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
  <%# user is not logged in, show signup and login links %>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path %> |
    <%= link_to 'Register Now!', new_user_registration_path %>
  <% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= simple_form_for (@link) do |f| %>
  
  <%= f.input :link, label: 'Your link please' %>
  
  <%= f.button :submit %>

<% end %>

app/views/links/create.html.erb
<h2>CREATE</h2>

app/views/links/index.html.erb
<h2>Links Index</h2>

<%= link_to "Add a link", new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<h2>SHOW</h2>

app/views/pages/index.html.erb
<h1>Home Page Son!</h1>